project_id = "kayngycfprnnknbptvic"

[functions.setup-master-admin]
verify_jwt = false

[functions.manage-college-admins]
verify_jwt = false

[functions.manage-staff]
verify_jwt = false

[functions.reset-admin-password]
verify_jwt = false